Rewrote the script so that it will run standalone, that is, anywhere it's in the same directory as topcat-*.jar, as well as in starjava/bin.  Simplified somewhat too, doesn't do so much clever stuff.

diff --git a/topcat/src/script/topcat b/topcat/src/script/topcat
--- a/topcat/src/script/topcat
+++ b/topcat/src/script/topcat
@@ -9,43 +9,50 @@
 
 #  Description:
 #     This shell script invokes the TOPCAT application.
+#     It's not very complicated, but performs some argument manipulation
+#     prior to invoking java with the right classpath and classname.
+#
+#     1. if a class path is specified using either the CLASSPATH
+#        environment variable or the -classpath flag to this script,
+#        it will be added to the application classpath
+#
+#     2. any command-line arguments which look like they are destined
+#        for java itself (starting with -D or -X) will be sent to java,
+#        and the others will be sent to the application
 
-#  Notes:
-#     This script locates a JVM and invokes it using the relevant class in 
-#     the tables jar file.  It currently does not do this using 'java -jar'
-#     as this would prevent any user additions to the classpath without
-#     additional machinery in both this script and the application
-#     classloading; these are required for use of JDBC.  May revise
-#     this at some stage.
+#  Requisites:
+#     - java should be on the path.
+#
+#     - relative to the directory in which this script is installed,
+#       one of the following jar files should exist and contain the
+#       TOPCAT classes:
+#          ./topcat-full.jar
+#          ./topcat-lite.jar
+#          ../../lib/topcat/topcat.jar
 
 #  Authors:
 #     MBT: Mark Taylor (Starlink)
 #-
 
-#  Find where this script is located.  We normally find this out by
-#  looking at where we were invoked from, but this can be overridden
-#  by setting TOPCAT_DIR (necessary if invocation is from another
-#  directory because of filesystem links).
-if test -z "$TOPCAT_DIR"
+# Set locations of acceptable jar files (relative to this script).
+topcat_jars="\
+ ../lib/topcat/topcat.jar\
+ topcat-full.jar\
+ topcat-lite.jar\
+"
+
+#  Find where this script is located.
+bindir="`dirname $0`"
+
+#  Locate the application jar file. 
+for j in $topcat_jars; do
+   if test -z "$appjar" -a -f "$bindir/$j"; then
+      appjar="$bindir/$j"
+   fi
+done
+if test ! -f "$appjar"
 then
-    bindir="`dirname $0`"
-else
-    bindir="$TOPCAT_DIR"
-fi
-
-#  Locate the application jar file.  This is relative to this script.
-
-appjar="$bindir/../lib/topcat/topcat.jar"
-if test ! -f "$appjar"; then
-   echo "Failed to locate $appjar."
-   exit 1
-fi
-
-#  Locate the java startup script.
-
-starjava="$bindir/starjava"
-if test ! -f "$starjava"; then
-   echo "Failed to locate '$bindir/starjava'."
+   echo 1>&2 "Can't find topcat classes in ${bindir} - looked for:$topcat_jars"
    exit 1
 fi
 
@@ -80,16 +87,10 @@ case "`uname`" in
   ;;
 esac
 
-
-#  Run topcat
-
-STARJAVA_DEFAULT_LOGGING="true"
-export STARJAVA_DEFAULT_LOGGING
-cmd="$starjava \
+#  Run topcat.
+cmd="java \
         $javaArgs \
-        -enableassertions \
         -Duk.ac.starlink.topcat.cmdname=topcat \
         -classpath \${CLASSPATH} uk.ac.starlink.topcat.Driver \
         $appArgs"
 eval "$cmd"
-
