This commit was manufactured by cvs2svn to create tag 'Starlink_ANT_1_5_2'.

diff --git a/ant/src/script/ant b/ant/src/script/ant
--- a/ant/src/script/ant
+++ b/ant/src/script/ant
@@ -1,37 +1,75 @@
-#! /bin/sh
+#!/bin/sh
 
 #   Copyright (c) 2001-2003 The Apache Software Foundation.  All rights
 #   reserved.
 
-# load system-wide ant configuration
-if [ -f "/etc/ant.conf" ] ; then 
-  . /etc/ant.conf
+# Starlink modifications.
+# Find Starlink Java
+if test "$STAR_JAVA" != ""; then
+   java="$STAR_JAVA"
+else
+
+   #  Fall-back Java is on current PATH.
+   java="java"
+
+   #  If $STARLINK is defined then try that. Look for JDK first as ANT 
+   #  needs that really. JRE is only useful for post build installations.
+   if test "$STARLINK" != ""; then
+      if test -r "$STARLINK/java/jdkhome"; then
+         java="`cat $STARLINK/java/jdkhome`/bin/java"
+      fi
+      if test -r "$STARLINK/java/jrehome"; then
+         java="`cat $STARLINK/java/jrehome`/bin/java"
+      fi
+   fi
+
+   #  If still not changed, look for Java in the standard installation.
+   if test "$java" = "java"; then
+      if test -r "/star/java/jdkhome"; then
+         java="`cat /star/java/jdkhome`/bin/java"
+      fi
+      if test -r "/star/java/jrehome"; then
+         java="`cat /star/java/jrehome`/bin/java"
+      fi
+   fi
 fi
 
+# Assume JDK to locate JAVA_HOME
+JAVA_HOME="`dirname $java`"
+JAVA_HOME="`dirname $JAVA_HOME`"
+JAVACMD="$java"
+
+echo $JAVA_HOME
+
+# load system-wide ant configuration
+#if [ -f "/etc/ant.conf" ] ; then 
+#  . /etc/ant.conf
+#fi
+
 # provide default values for people who don't use RPMs
-if [ -z "$rpm_mode" ] ; then
-  rpm_mode=false;
-fi
+#if [ -z "$rpm_mode" ] ; then
+#  rpm_mode=false;
+#fi
 if [ -z "$usejikes" ] ; then
   usejikes=false;
 fi
 
 # load user ant configuration
-if [ -f "$HOME/.antrc" ] ; then 
-  . "$HOME/.antrc"
-fi
+#if [ -f "$HOME/.antrc" ] ; then 
+#  . $HOME/.antrc
+#fi
 
 # OS specific support.  $var _must_ be set to either true or false.
-cygwin=false;
-darwin=false;
-case "`uname`" in
-  CYGWIN*) cygwin=true ;;
-  Darwin*) darwin=true
-           if [ -z "$JAVA_HOME" ] ; then
-             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home   
-           fi
-           ;;
-esac
+#cygwin=false;
+#darwin=false;
+#case "`uname`" in
+#  CYGWIN*) cygwin=true ;;
+#  Darwin*) darwin=true
+#           if [ -z "$JAVA_HOME" ] ; then
+#             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home   
+#           fi
+#           ;;
+#esac
 
 if [ -z "$ANT_HOME" ] ; then
   # try to find ANT
@@ -71,59 +109,60 @@ if [ -z "$ANT_HOME" ] ; then
 fi
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-  [ -n "$ANT_HOME" ] &&
-    ANT_HOME=`cygpath --unix "$ANT_HOME"`
-  [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-  [ -n "$CLASSPATH" ] &&
-    CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
-fi
-
-# set ANT_LIB location
-ANT_LIB="${ANT_HOME}/lib"
-
-if [ -z "$JAVACMD" ] ; then 
-  if [ -n "$JAVA_HOME"  ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then 
-      # IBM's JDK on AIX uses strange locations for the executables
-      JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-      JAVACMD="$JAVA_HOME/bin/java"
-    fi
-  else
-    JAVACMD=`which java 2> /dev/null `
-    if [ -z "$JAVACMD" ] ; then 
-        JAVACMD=java
-    fi
-  fi
-fi
+#if $cygwin ; then
+#  [ -n "$ANT_HOME" ] &&
+#    ANT_HOME=`cygpath --unix "$ANT_HOME"`
+#  [ -n "$JAVA_HOME" ] &&
+#    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+#  [ -n "$CLASSPATH" ] &&
+#    CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+#fi
+#
+## set ANT_LIB location
+#ANT_LIB="${ANT_HOME}/lib"
+#
+#if [ -z "$JAVACMD" ] ; then 
+#  if [ -n "$JAVA_HOME"  ] ; then
+#    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then 
+#      # IBM's JDK on AIX uses strange locations for the executables
+#      JAVACMD="$JAVA_HOME/jre/sh/java"
+#    else
+#      JAVACMD="$JAVA_HOME/bin/java"
+#    fi
+#  else
+#    JAVACMD=`which java 2> /dev/null `
+#    if [ -z "$JAVACMD" ] ; then 
+#        JAVACMD=java
+#    fi
+#  fi
+#fi
  
-if [ ! -x "$JAVACMD" ] ; then
-  echo "Error: JAVA_HOME is not defined correctly."
-  echo "  We cannot execute $JAVACMD"
-  exit 1
-fi
+#if [ ! -x "$JAVACMD" ] ; then
+#  echo "Error: JAVA_HOME is not defined correctly."
+#  echo "  We cannot execute $JAVACMD"
+#  exit 1
+#fi
 
 if [ -n "$CLASSPATH" ] ; then
   LOCALCLASSPATH="$CLASSPATH"
 fi
 
 # in rpm_mode get ant/optional/xml parser&api from JAVALIBDIR 
-if $rpm_mode; then
-  JAVALIBDIR=/usr/share/java
-  for i in ant ant-optional jaxp_parser xml_apis 
-  do
-    if [ -z "$LOCALCLASSPATH" ] ; then
-      LOCALCLASSPATH="$JAVALIBDIR/$i.jar"
-    else
-      LOCALCLASSPATH="$JAVALIBDIR/$i.jar":"$LOCALCLASSPATH"
-    fi
-  done
+#if $rpm_mode; then
+#  JAVALIBDIR=/usr/share/java
+#  for i in ant ant-optional jaxp_parser xml_apis 
+#  do
+#    if [ -z "$LOCALCLASSPATH" ] ; then
+#      LOCALCLASSPATH="$JAVALIBDIR/$i.jar"
+#    else
+#      LOCALCLASSPATH="$JAVALIBDIR/$i.jar":"$LOCALCLASSPATH"
+#    fi
+#  done
 
-  # in rpm mode ant/lib is in /usr/share/java/ant
-  ANT_LIB="${JAVALIBDIR}/ant"
-fi
+# in rpm mode ant/lib is in /usr/share/java/ant
+#  ANT_LIB=${JAVALIBDIR}/ant
+#
+#fi
 
 # add in the dependency .jar files in non-RPM mode (the default)
 for i in "${ANT_LIB}"/*.jar
@@ -138,6 +177,11 @@ do
     fi
   fi
 done
+
+# PWD: locate the JUnit jar file and add that.
+if [ -f "$ANT_LIB/junit/junit.jar" ]; then
+   LOCALCLASSPATH="${ANT_LIB}/junit/junit.jar:${LOCALCLASSPATH}"
+fi
 
 if [ -n "$JAVA_HOME" ] ; then
   if [ -f "$JAVA_HOME/lib/tools.jar" ] ; then
@@ -158,11 +202,11 @@ if [ -n "$JAVA_HOME" ] ; then
       done
     fi
   fi
-else
-  echo "Warning: JAVA_HOME environment variable is not set (or not exported)."
-  echo "  If build fails because sun.* classes could not be found"
-  echo "  you will need to set the JAVA_HOME environment variable"
-  echo "  to the installation directory of java."
+#else
+#  echo "Warning: JAVA_HOME environment variable is not set (or not exported)."
+#  echo "  If build fails because sun.* classes could not be found"
+#  echo "  you will need to set the JAVA_HOME environment variable"
+#  echo "  to the installation directory of java."
 fi
 
 # Allow Jikes support (off by default)
@@ -171,13 +215,13 @@ if $usejikes; then
 fi
 
 # For Cygwin, switch paths to Windows format before running java
-if $cygwin; then
-  ANT_HOME=`cygpath --windows "$ANT_HOME"`
-  JAVA_HOME=`cygpath --windows "$JAVA_HOME"`
-  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
-  LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
-  CYGHOME=`cygpath --windows "$HOME"`
-fi
+#if $cygwin; then
+#  ANT_HOME=`cygpath --windows "$ANT_HOME"`
+#  JAVA_HOME=`cygpath --windows "$JAVA_HOME"`
+#  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+#  LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
+#  CYGHOME=`cygpath --windows "$HOME"`
+#fi
 
 if [ -n "$CYGHOME" ]; then
   if [ -n "$JIKESPATH" ]; then
@@ -193,4 +237,3 @@ else
     "$JAVACMD" $ANT_OPTS -classpath "$LOCALCLASSPATH" -Dant.home="${ANT_HOME}" org.apache.tools.ant.Main $ANT_ARGS "$@"
   fi
 fi
-
